#!/bin/bash

bootSize='199MiB'
swapSize='4096MiB'
timezone='Asia/Muscat'
mirror='https://dl-cdn.alpinelinux.org/alpine'
arch='x86_64'
branch='edge'
version='v3.16'
pool='rpool'
hostname='linux'
user='user'
password='0000'

packages_list() {

    packages+=(
        # desktop
        dbus dbus-openrc dbus-x11 iio-sensor-proxy
        ibus ibus-bash-completion
        udev-init-scripts udev-init-scripts-openrc
        eudev eudev-openrc eudev-libs
        musl-locales openrc-bash-completion
        xorg-server mesa-dri-gallium xf86-input-libinput
        polkit polkit-openrc polkit-elogind polkit-common polkit-elogind-libs
        elogind elogind-openrc elogind-bash-completion
        # hardware
        hwids hwids-net hwids-pci hwids-usb hwids-udev
        # wayland
        xwayland weston-xwayland
        # hardware
        bolt pciutils
        tpm2-tools tpm2-tools-bash-completion
        # efi boot
        efibootmgr
        # base
        sudo bash bash-completion build-base fakeroot shadow rsyslog rsyslog-openrc sed attr dialog which grep util-linux util-linux-openrc util-linux-login util-linux-bash-completion pciutils usbutils binutils findutils readline lsof less nano curl wget coreutils gawk diffutils autoconf
        # utilities
        openssl ncurses-dev
        # git
        git git-bash-completion
        # compression
        brotli zstd zlib libzip zip lz4 lzo unzip xz
        # disks
        e2fsprogs lvm2 os-prober gptfdisk dosfstools mtools ntfs-3g ntfs-3g-progs xfsprogs hfsprogs exfatprogs f2fs-tools udftools sfdisk sgdisk udisks2 mmc-utils jfsutils
        # firewall
        gufw ufw ufw-openrc ufw-bash-completion iptables iptables-openrc
        # network
        ethtool ethtool-bash-completion rsync rsync-openrc
        networkmanager networkmanager-openrc networkmanager-common networkmanager-bash-completion networkmanager-elogind networkmanager-wwan networkmanager-wifi networkmanager-bluetooth networkmanager-openvpn networkmanager-initrd-generator
        # wireless
        wireless-regdb wireless-tools iwd iwd-openrc
        # sound
        alsa-plugins-pulse alsa-lib
        pipewire pipewire-media-session pipewire-alsa pipewire-libs pipewire-pulse pipewire-tools
        # bluetooth
        bluez-alsa bluez-alsa-openrc bluez-alsa-utils
        # firmware
        fwupd fwupd-openrc fwup-bash-completion fwupd-efi fwupd-plugin-bios fwupd-plugin-cpu fwupd-plugin-tpm fwupd-plugin-nvme fwupd-plugin-ata
        # trackpad
        xf86-input-synaptics xf86-input-mtrack
        # browser
        chromium-chromedriver
        # fonts
        font-hack font-adobe-source-code-pro
        font-arabic-misc
        font-noto font-noto-arabic font-noto-kufi-arabic font-noto-naskh-arabic
        font-inter font-opensans font-roboto font-xfree86-type1
        ttf-dejavu ttf-font-awesome ttf-freefont ttf-droid
        font-awesome font-awesome-free font-awesome-brands
        # mesa
        mesa mesa-vulkan-layers
        # intel GPU
        mesa-vulkan-intel intel-media-driver
        # vulkan
        vulkan-loader vulkan-tools vulkan-validation-layers
        # nvidia GPU
        nvidia-src
        # keyboard
        setxkbmap
        # timezone
        tzdata
        # gvfs
        gvfs gvfs-afc gvfs-archive gvfs-dev gvfs-fuse gvfs-mtp gvfs-nfs gvfs-smb
    )

    if grep -q btrfs /root/list; then
        packages+=(
            btrfs-progs btrfs-progs-extra btrfs-progs-libs btrfs-progs-bash-completion
        )
    fi

    if grep -q gnome /root/list; then
        packages+=(
            # gnome session
            gdm gdm-openrc mutter mutter-schemas gnome-desktop gnome-desktop-lang gnome-session gnome-shell gnome-shell-schemas gnome-shell-extensions gnome-menus gnome-initial-setup gnome-control-center gnome-control-center-bash-completion gnome-tweaks gnome-colors-common gsettings-desktop-schemas udisks2-bash-completion tracker-bash-completion pinentry-gnome gst-plugin-pipewire
            # connector
            chrome-gnome-shell gnome-browser-connector
            # theme
            adwaita-icon-theme hicolor-icon-theme
            # gnome tools
            gnome-keyring gnome-terminal gnome-disk-utility gnome-system-monitor file-roller
            # nautilus
            nautilus
            # text
            gedit gedit-plugins py3-cairo
            # firmware
            gnome-firmware-updater
            # gnome theme
            arc-theme arc-dark arc-dark-gnome
            # gedit spell check
            aspell hunspell hunspell-en nuspell
            # network
            network-manager-applet
        )
    fi

    if grep -q kde /root/list; then
        packages+=(
            # desktop
            polkit-kde-agent-1
            # hardware
            solid
            # sddm
            sddm sddm-openrc sddm-kcm sddm-breeze
            # plasma
            plasma-desktop plasma-workspace plasma-workspace-lang plasma-integration plasma-systemmonitor plasma-firewall plasma-settings plasma-pass plasma-vault
            # system
            ksysguard
            # kwallet
            kwallet kwallet-pam kwalletmanager kio-kwallet
            # theme
            kiconthemes breeze breeze-gtk breeze-icons breeze-grub kholidays
            # bluetooth
            bluedevil
            # power
            powerdevil
            # wayland
            plasma-wayland-protocols kwayland kwayland-integration
            # system
            systemsettings kde-gtk-config
            # network
            plasma-nm
            # firewall
            iproute2 net-tools
            # audio
            plasma-pa kmix
            # kde
            ki18n kwin kinit kcron kdecoration krecorder kscreen kscreenlocker kactivities kmenuedit kinfocenter konsole kde-gtk-config kio-fuse
            # file manager
            dolphin dolphin-plugins index kfind
        )
    fi

    if grep -q mate /root/list; then
        packages+=(
            # display manager
            lightdm lightdm-openrc lightdm-bash-completion slick-greeter
            # mate desktop
            mate-desktop mate-common mate-polkit
            mate-session-manager
            mate-panel mate-control-center mate-tweak mate-utils mate-media
            mate-settings-daemon mate-notification-daemon
            mate-terminal mate-system-monitor mate-power-manager mate-calc
            # mate theme
            mate-icon-theme hicolor-icon-theme mint-y-icons
            # mate applet
            mate-applets mate-sensors-applet mate-indicator-applet
            # mate menu
            mate-menus mozo
            # file manager
            caja caja-extensions
            # text editor
            pluma
            # view
            atril eom
            # archieve
            engrampa
        )
    fi

    if grep -q workstation /root/list; then

        if grep -q gnome /root/list; then
            packages+=(
                # gnome apps
                gnome-software gnome-software-plugin-apk gnome-software-plugin-flatpak gnome-photos gnome-music gnome-clocks gnome-contacts gnome-calculator gnome-maps gnome-logs gnome-remote-desktop gnome-screenshot gnome-boxes gnome-calendar gnome-sound-recorder gnome-font-viewer gnome-colors gnome-bluetooth gnome-podcasts gnome-characters gnome-builder gnome-shortwave getting-things-gnome sushi simple-scan
                # config
                dconf dconf-bash-completion dconf-editor dconf-editor-bash-completion
                # web
                epiphany
                # documents
                evince evince-nautilus
                # photos
                gthumb eog shotwell
                # mail
                geary
                # sound
                gnome-metronome lollypop blanket
                # other
                glade ghex baobab confy
                # bluetooth
                blueman
                # tools
                karchive ark
                # flatpak
                xdg-desktop-portal xdg-desktop-portal-gnome xdg-desktop-portal-gtk xdg-user-dirs
            )
        fi

        if grep -q kde /root/list; then
            packages+=(
                # plasma
                plasma-camera plasma-dialer plasma-videoplayer plasma-phonebook plasma-browser-integration plasma-thunderbolt plasma-disks
                # kde
                shelf knetattach kmail kiconthemes ktorrent kdeconnect akregator kphotoalbum kmymoney kdeedu-data kalk rocs calligra marble haruna clip buho vvave index communicator qrca kdesdk-thumbnailers knotes falkon sweeper step kmousetool kclock krename kcolorchooser kunitconversion
                # theme
                materia-kde materia-kde-plasma materia-kde-kvantum
                # disks
                partitionmanager isoimagewriter
                # print
                print-manager
                # mobile
                koko angelfish calindori
                # screen
                spectacle kscreenlocker plasma-bigscreen kruler
                # image
                gwenview
                # audio
                audiocd-kio juk kwave elisa
                # video
                kmediaplayer kdenlive dragon
                # YouTube
                plasmatube audiotube
                # camera
                kamera kamoso
                # software
                discover discover-backend-apk discover-backend-flatpak discover-backend-fwupd
                # editor
                kwrite kate kile ktexteditor nota kompare
                # spelling
                sonnet
                # office
                kcalc okular skanlite
                # input
                plasma-remotecontrollers
                # draw
                kolourpaint
                # math
                cantor kalgebra kig kmplot
                # music
                minuet
                # flatpak
                xdg-desktop-portal xdg-desktop-portal-kde xdg-user-dirs
                # hex
                okteta
            )
        fi

        packages+=(
            # shell
            starship
            # wine
            wine vkd3d
            # thumbnail
            ffmpegthumbnailer
            # mkimage
            abuild alpine-sdk apk-tools alpine-conf mkinitfs xorriso squashfs-tools
            # fonts tools
            font-manager font-viewer
            # office
            libreoffice-base libreoffice-common libreoffice-writer libreoffice-math libreoffice-calc libreoffice-draw libreoffice-lang-en_us libreoffice-lang-ar
            # google
            google-authenticator
            # mail
            thunderbird
            # music
            amberol musescore
            # audio
            ardour tenacity calf calf-jack calf-lv2
            # video edit
            shotcut pitivi x265
            # video subtitle
            gaupol
            # book
            foliate
            # openvc
            opencv py3-opencv
            # python
            black
            # JavaScript
            npm npm-bash-completion nodejs esbuild reason
            # code
            code-oss code-oss-bash-completion lapce codeblocks
            # code format
            prettier tidyhtml
            # html/css to pdf
            weasyprint
            # screenshot
            flameshot
            # electronic
            kicad
            # screen
            obs-studio kooha peek
            # video
            mplayer totem celluloid
            # photos
            krita gimp inkscape gmic curtail
            # printer
            cups cups-openrc cups-pdf bluez-cups
            # driver
            xinput gkraken ccid solaar razercfg razercfg-gui razergenie openrazer
            # math
            mathjax2
            # finance
            homebank
            # 2d
            tiled
            # 3d
            blender freecad godot leocad solvespace goxel
            # 3d printer
            cura
            # text editor
            kakoune
            # mauikit
            mauikit mauikit-accounts mauikit-filebrowsing mauikit-imagetools mauikit-texteditor
            # bitcoin
            bitcoin bitcoin-openrc
            # game emu
            pcsx2 dolphin-emu xwiimote pcsxr
            # rust
            rust rustfmt rust-analysis cargo
            # go
            go
            # php
            composer php82 php82-bcmath php82-bz2 php82-cgi php82-curl php82-common php82-phpdbg php82-dom php82-exif php82-fileinfo php82-fpm php82-gd php82-gettext php82-iconv php82-intl php82-litespeed php82-mbstring php82-mysqli php82-mysqlnd php82-opcache php82-openssl php82-phar php82-pear php82-session php82-snmp php82-soap php82-xml php82-zip
            # android
            gradle android-tools android-tools-bash-completion go-mtpfs scrcpy scrcpy-bash-completion
            # iPhone/iPod/mac
            ifuse ideviceinstaller idevicerestore libirecovery libirecovery-progs libideviceactivation libimobiledevice libimobiledevice-progs
            # pdf
            corepdf pdfarranger poppler
            # drives
            onedrive onedrive-openrc
            # twitter
            cawbird
            # Corsair
            ckb-next
            # RGB
            openrgb
            # plan
            planner
            # music player
            amberol sublime-music
            # music server
            navidrome navidrome-openrc
            # youtube
            ffmpeg yt-dlp yt-dlp-bash-completion pipe-viewer-gtk audiotube tartube youtube-viewer-gtk
            # javascript/css
            minify minify-bash-completion
            # photos
            darktable
            # drawing
            drawing
            # remote
            remmina
            # touch
            touchegg touchegg-openrc
            # CPU
            corectrl
            # cctv
            zoneminder zoneminder-openrc
            # iso
            thumbdrives
        )

        if grep -q gnome /root/list; then
            packages+=(
                libreoffice-gnome
            )
        fi

    fi

    if grep -q server /root/list; then

        packages+=(
            # system
            rsyslog rsyslog-openrc rsyslog-mysql rsyslog-tls rsyslog-http
            # SSL/TLS
            certbot
            # php
            php81 php81-bcmath php81-brotli php81-bz2 php81-cgi php81-curl php81-common php81-phpdbg php81-dom php81-exif php81-fileinfo php81-fpm php81-gd php81-gettext php81-iconv php81-intl php81-litespeed php81-mbstring php81-memcache php81-memcached php81-mysqli php81-mysqlnd php81-opcache php81-openssl php81-phar php81-pear php81-redis php81-session php81-snmp php81-soap php81-xml php81-zip php81-pecl-imagick
            # php admin
            phpmyadmin
            # database
            mariadb
            # mail
            postfix postfix-openrc postfix-mysql postfix-pcre postfixadmin
            dovecot dovecot-openrc dovecot-submissiond dovecot-ldap dovecot-lmtpd dovecot-pop3d dovecot-sql dovecot-mysql
            opendkim opendkim-utils
            cyrus-sasl
            # tools
            imagemagick redis redis-openrc memcached memcached-openrc
            # server
            litespeed litespeed-openrc
            # http
            hetty
            # cab
            cabextract
        )

    fi

}

menu() {

    echo -e "\n --> $1:\n"
    output=$2
    shift 2
    options=($@)
    i=0
    while true; do
        for option in ${options[@]}; do
            if [[ $option == ${options[$i]} ]]; then
                echo -e "\t\e[7m$option\e[0m"
            else
                echo -e "\t$option"
            fi
        done
        read -sn3 key
        if [[ $key == $(echo -en "\e[A") ]] && [[ $i -gt 0 ]]; then
            i=$(($i-1))
        elif [[ $key == $(echo -en "\e[B") ]] && [[ $i -lt ${#options[@]} ]]; then
            i=$(($i+1))
        elif [[ -z $key ]]; then
            break
        fi
        echo -en "\e[${#options[@]}A"
    done
    printf -v $output "${options[$i]}"

}

setup_drive() {

    echo '# created by Saif AlSubhi'
    printf -- '-%.0s' {1..100}; echo ''
    lsblk -o name,type,fstype,size,fsused,fsuse%,mountpoint,label,model
    printf -- '-%.0s' {1..100}; echo ''

    drives=($(ls /dev/ | grep '^nvme.\{3\}$\|^sd.\{1\}$'))

    for i in ${!drives[@]}; do
        drives[$i]="/dev/${drives[$i]}"
    done

    menu 'select a drive' drive ${drives[@]}

    if ls $drive* | grep -q "$drive.\{1\}$"; then
        partitions=($(ls $drive*))
        menu 'select a root partition or use the complete drive ' partition ${partitions[@]}
        if [[ $drive != $partition ]] ; then
            root_drive=$partition
            partitions=($(ls $drive* | grep -v $drive | grep -v $partition | grep "$drive.\{1\}$"))
            menu 'select a boot partition to mount ' partition ${partitions[@]}
            boot_drive=$partition
        fi
    fi

    filesystems=(btrfs zfs xfs ext4 exfat ntfs)
    menu 'select a filesystem' filesystem ${filesystems[@]}

    computers=(minimal workstation server)
    menu 'select a computer' computer ${computers[@]}

    desktops=(gnome kde mate none)
    menu 'select a desktop' desktop ${desktops[@]}

    bootloaders=(grub syslinux)
    menu 'select a bootloader' bootloader ${bootloaders[@]}

    echo -e "\n"

    echo ">>> adding options"
    echo "drive=$drive" > /root/list
    echo "filesystem=$filesystem" >> /root/list
    echo "computer=$computer" >> /root/list
    echo "desktop=$desktop" >> /root/list
    echo "bootloader=$bootloader" >> /root/list

    if ! test sgdisk; then
        echo ">>> installing sgdisk"
        apk add sgdisk
    fi

    if [[ ! $root_drive ]]; then

        echo ">>> wiping filesystm"
        wipefs -a -f $drive
        echo ">>> deleting partitions"
        sgdisk -Z $drive
        echo ">>> creating GPT"
        sgdisk -U $drive

        echo ">>> creating boot partition"
        sgdisk -n 0:0:+$bootSize -c 0:efi -t 0:ef00 $drive
        boot_drive=$drive"1"
        echo "boot_drive=$boot_drive" >> /root/list

        if [[ $swapSize != '0' ]]; then
            echo ">>> creating swap partition"
            sgdisk -n 0:0:+$swapSize -c 0:swap -t 0:8200 $drive
            swap_drive=$drive"2"
            echo "swap_drive=$swap_drive" >> /root/list
        fi

        echo ">>> creating root partition"

        if grep -q zfs /root/list; then
            sgdisk -n 0:0:0 -c 0:$pool -t 0:bf00 $drive
        else
            sgdisk -n 0:0:0 -c 0:linux -t 0:8300 $drive
        fi

        root_drive=$drive"3"
        echo "root_drive=$root_drive" >> /root/list

        echo ">>> reading partition tables"
        mdev -s

        echo ">>> creating boot filesystem"
        mkfs.vfat -F32 -n BOOT $boot_drive

        if [[ $swap_drive ]]; then
            echo ">>> creating swap filesystem"
            mkswap $swap_drive
        fi

    fi

    echo ">>> creating root filesystem"
    if grep -q zfs /root/list; then
        create_zfs
        set_zfs
    elif grep -q btrfs /root/list; then
        mkfs.btrfs -f -L btrfs $root_drive
    elif grep -q ext4 /root/list; then
        mkfs.ext4 -f -L ext4 $root_drive
    elif grep -q exfat /root/list; then
        mkfs.exfat -f -L exfat $root_drive
    elif grep -q ntfs /root/list; then
        mkfs.ntfs -f -C -L ntfs $root_drive
    elif grep -q xfs /root/list; then
        mkfs.xfs -f -L xfs $root_drive
    fi

    mount_root
    mount_boot
    install_base

}

create_zfs() {

    echo ">>> loading ZFS modules"
    /sbin/modprobe zfs
    echo ">>> checking ZFS modules"
    if ! lsmod | grep -qi zfs; then
       echo 'ERROR: ZFS modules are missing'
       create_rootfs
    fi
    echo ">>> creating ZFS pool"
    zpool create -f -o ashift=12 -o autotrim=on \
    -o cachefile=/etc/zfs/zpool.cache \
    -O recordsize=8192 -O compression=lz4 -O acltype=posixacl \
    -O devices=off -O xattr=sa -O relatime=off -O atime=off \
    -O dnodesize=legacy -O normalization=formD \
    -O canmount=noauto -O mountpoint=legacy -R /mnt $pool $root_drive
    echo ">>> checking ZFS pool"
    zpool status

}

set_zfs() {

    echo ">>> setting ZFS pool as rootfs"
    zpool set bootfs=$pool $pool
    echo ">>> setting ZFS cache"
    mkdir -p /mnt/etc/zfs
    cp /etc/zfs/zpool.cache /mnt/etc/zfs/zpool.cache
    echo ">>> adding ZFS options"
    mkdir -p /mnt/etc/modprobe.d/
    echo "options zfs l2arc_noprefetch=0" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs l2arc_write_max=536870912" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs l2arc_write_boost=1073741824" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs l2arc_headroom=12" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_arc_max=1073741824" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_arc_min=268435456" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_prefetch_disable=0" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_top_maxinflight=320" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_txg_timeout=15" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_scheduler=deadline" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_async_read_min_active=8" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_async_read_max_active=32" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_async_write_min_active=8" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_async_write_max_active=32" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_sync_write_min_active=8" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_sync_write_max_active=32" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_sync_read_min_active=8" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_sync_read_max_active=32" >> /mnt/etc/modprobe.d/zfs.conf

}

mount_root() {

    if grep -q zfs /root/list; then
        echo ">>> exporting zpool"
        zpool export $pool
        echo ">>> importing zpool"
        zpool import $pool -d $root_drive -R /mnt
        echo ">>> mounting zfs dataset"
        mount -t zfs $pool /mnt
    else
        echo ">>> mounting root drive"
        mount $root_drive /mnt
    fi

    if ! mountpoint -q /mnt; then
        exit
    fi

    if [[ ! -d /mnt/boot ]]; then
        mkdir -p /mnt/boot
    fi

    if [[ ! -d /mnt/boot/EFI ]]; then
        mkdir -p /mnt/boot/EFI
    fi

}

mount_boot() {

    echo ">>> mounting boot drive"
    mount $boot_drive /mnt/boot

}

install_base() {

    echo ">>> updating packages"
    echo "$mirror/$branch/main" > /etc/apk/repositories
    echo "$mirror/$branch/community" >> /etc/apk/repositories
    echo "$mirror/$branch/testing" >> /etc/apk/repositories
    echo "$mirror/$version/main" >> /etc/apk/repositories
    echo "$mirror/$version/community" >> /etc/apk/repositories

    echo ">>> installing alpine-base"
    apk add --root=/mnt --initdb alpine-base --keys-dir /etc/apk/keys --repositories-file /etc/apk/repositories

    echo ">>> copying repositories"
    cp /etc/apk/repositories /mnt/etc/apk/repositories

    echo ">>> creating /dev/null"
    rm /mnt/dev/null
    cp /dev/null /mnt/dev/null
    chmod 0666 /mnt/dev/null

    set_network
    set_fstab
    setup_linux

}

set_network() {

    echo ">>> adding name resolution"
    echo 'nameserver 1.0.0.1' >> /mnt/etc/resolv.conf
    echo 'nameserver 8.8.8.8' >> /mnt/etc/resolv.conf

    echo ">>> adding interfaces"
    cat > /mnt/etc/network/interfaces << EOF
auto lo
iface lo inet loopback
EOF

}

set_fstab() {

    echo ">>> setting fstab"
    echo $filesystem >> /mnt/etc/modules

    if grep -q zfs /root/list; then
        echo "$pool / $filesystem rw,nodev,noauto,xattr,posixacl 0 0" > /mnt/etc/fstab
    else
        echo "$(blkid $root_drive -o export | grep ^UUID=) / $filesystem ssd,nofail,rw,discard,noatime,commit=64,autodefrag,compress=zstd:10 0 0" > /mnt/etc/fstab
    fi

    echo "$(blkid $boot_drive -o export | grep ^UUID=) /boot vfat rw,noatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro 0 0" >> /mnt/etc/fstab

    echo "$(blkid $swap_drive -o export | grep ^UUID=) none swap sw 0 0" >> /mnt/etc/fstab

}

setup_linux() {

    install_linux
    install_packages
    set_locale
    set_timezone
    set_host
    change_root

}

install_linux() {

    if [[ -f /mnt/lib/apk/db/lock ]]; then
        rm /mnt/lib/apk/db/lock
        apk fix --root=/mnt
    fi

    if grep -q zfs /root/list; then
        list='linux-lts'
    else
        list='linux-edge'
    fi

    list+=' amd-ucode intel-ucode linux-pam'
    list+=' zfs zfs-openrc zfs-libs'
    list+=' linux-firmware-intel linux-firmware-i915'
    list+=' linux-firmware-amd linux-firmware-amd-ucode'
    list+=' linux-firmware-nvidia'
    list+=' linux-firmware-amdgpu'
    list+=' linux-firmware-other'
    list+=' linux-firmware-brcm linux-firmware-qca'
    list+=' linux-firmware-rtlwifi linux-firmware-rtl_bt linux-firmware-rtl_nic'

    echo ">>> installing linux"
    apk add --root=/mnt $list

}

install_packages() {

    echo ">>> packages list"
    packages=''
    packages_list

    list=''
    for i in ${!packages[@]}; do
        list+=' '
        list+=${packages[$i]}
    done
    echo ">>> installing packages"
    apk add --root=/mnt $list
    apk fix --root=/mnt

}

set_locale() {

    echo ">>> setting locale"
    sed -i 's|#unicode="NO"|unicode="YES"|' /mnt/etc/rc.conf

}

set_timezone() {

    echo ">>> setting timezone"
    if [[ -f /mnt/usr/share/zoneinfo/$timezone ]]; then
        install -Dm 0644 /mnt/usr/share/zoneinfo/$timezone /mnt/etc/localtime
        echo $timezone > /mnt/etc/timezone
    else
        read -p " --- timezone Asia/Muscat: " timezone
        set_timezone
    fi

}

set_host() {

    echo ">>> setting hostname"
    echo "$hostname" > /mnt/etc/hostname
    echo "127.0.0.1 localhost $hostname" > /mnt/etc/hosts
    echo "::1       localhost $hostname" >> /mnt/etc/hosts

}

change_root() {

    echo ">>> loading modules"
    /sbin/modprobe efivars
    echo ">>> copying install script"
    cp /root/list /mnt/root/list
    cp /root/install /mnt/root/install
    echo ">>> changing root"
    echo '' > /mnt/root/chroot
    mount --bind /proc /mnt/proc
    mount --bind /dev /mnt/dev
    mount --bind /sys /mnt/sys
    chroot /mnt bash /root/install

}

configure() {

    disable_root
    create_user
    setup_desktop

}

disable_root() {

    usermod -s /bin/bash root
    echo ">>> changing root password"
    echo -en "$password\n$password" | passwd root
    echo ">>> disabling root login"
    passwd -l root

}

create_user() {

    echo ">>> creating user"
    if id $user &>/dev/null; then
        userdel $user
    fi
    echo "%$user ALL=(ALL) ALL" > /etc/sudoers.d/$user
    chmod 0400 /etc/sudoers.d/$user
    echo -en "$password\n$password" | adduser -h /home/$user -s /bin/bash -g $user $user
    adduser $user video
    adduser $user audio
    adduser $user input
    adduser $user netdev

}

setup_desktop() {

    enable_services
    configure_alpine
    if grep -q mate /root/list; then
        configure_lightdm
    fi
    add_commands
    install_mkinitfs
    if grep -q syslinux /root/list; then
        install_syslinux
    fi
    if grep -q grub /root/list; then
        install_grub
    fi
    finish

}

enable_services() {

    echo ">>> enabling services"

    rc-update add devfs sysinit
    rc-update add dmesg sysinit
    rc-update add mdev sysinit
    rc-update add hwdrivers sysinit

    rc-update add udev sysinit

    rc-update add localmount boot
    rc-update add lvm boot
    rc-update add swap boot

    rc-update add hwclock boot
    rc-update add modules boot
    rc-update add sysctl boot
    rc-update add hostname boot
    rc-update add bootmisc boot
    rc-update add syslog boot
    rc-update add networking boot

    rc-update add mount-ro shutdown
    rc-update add killprocs shutdown
    rc-update add savecache shutdown

    if grep -q zfs /root/list; then
        rc-update add zfs-import boot
        rc-update add zfs-mount boot
        rc-update add zfs-share boot
        rc-update add zfs-zed boot
        rc-update add zfs-load-key boot
    fi

    if grep -q btrfs /root/list; then
        cat > /etc/init.d/btrfs-scan << EOF
#!/sbin/openrc-run
name="btrfs-scan"
depend() {
  before localmount
}
start() {
  /sbin/btrfs device scan
}
EOF
        chmod +x /etc/init.d/btrfs-scan
        rc-update add btrfs-scan boot
    fi

    rc-update add dbus default
    rc-update add elogind default
    rc-update add polkit default

    rc-update add udev default
    rc-update add udev-settle default
    rc-update add udev-trigger default
    rc-update add udev-postmount default

    rc-update add rsyncd default
    rc-update add networkmanager default
    rc-update add networkmanager-dispatcher default

    rc-update add bluealsa default
    rc-update add bluetooth default
    rc-update add fwupd default
    rc-update add ufw default

    rc-update add iwd default

    rc-update add fancontrol default
    rc-update add sensord default

    if grep -q gnome /root/list; then
        rc-update add gdm default
    fi

    if grep -q kde /root/list; then
        rc-update add sddm default
    fi

    if grep -q mate /root/list; then
        rc-update add lightdm default
    fi

    if grep -q workstation /root/list; then
        rc-update add cupsd default
    fi

    if grep -q server /root/list; then
        rc-update add mariadb default
        rc-update add litespeed default
        rc-update add postfix default
        rc-update add dovecot default
        rc-update add opendkim default
        mkdir /var/mysql && chown -R mysql:mysql /var/mysql
        mkdir /var/log/mysql && chown -R mysql:mysql /var/log/mysql
    fi

}

configure_alpine() {

    echo ">>> configuring alpine"

    if [[ -d /etc/NetworkManager/ ]]; then
        cat > /etc/NetworkManager/NetworkManager.conf << EOF
[main]
dhcp=internal
plugins=ifupdown,keyfile
[ifupdown]
managed=true
[device]
wifi.backend=iwd
EOF
    fi

    echo ">>> configuring pipewire"
    cat >> /etc/security/limits.conf << EOF
@audio - rtprio 88
@audio - memlock 256
@audio - nice -11
EOF

    if [ ! -d /etc/pipewire ]; then
        mkdir /etc/pipewire
    fi
    cp /usr/share/pipewire/pipewire.conf /etc/pipewire/
    if ! grep -q 'snd_seq' /etc/modules; then
        echo snd_seq >> /etc/modules
    fi

    if [[ ! -d /usr/share/icons/windows-11-icons/ ]]; then
        echo ">>> cloning Windows-11-icons"
        git clone https://github.com/0free/windows-11-icons.git
        mv windows-11-icons/ /usr/share/icons/
    fi

    echo ">>> configuring firewall"
    sed -i 's|IPV6=yes|IPV6=no|' /etc/default/ufw
    sed -i 's|"DROP"|"REJECT"|g' /etc/default/ufw
    sed -i 's|ENABLED=no|ENABLED=yes|' /etc/ufw/ufw.conf

    if grep -q kde /root/list; then
        if [[ ! -d kde/ ]]; then
            echo ">>> configuring kde"
            git clone https://github.com/0free/kde.git
            mv /kde/.config/ /home/$user/
            rm -r kde/
        fi
    fi

}

configure_lightdm() {

    echo ">>> configuring lightdm"
    sed -i 's|#allow-guest=.*|allow-guest=false|' /etc/lightdm/lightdm.conf
    sed -i 's|#autologin-guest=.*|autologin-guest=false|' /etc/lightdm/lightdm.conf
    sed -i "s|#autologin-user=.*|autologin-user=$user|" /etc/lightdm/lightdm.conf
    sed -i 's|#autologin-user-timeout=.*|autologin-user-timeout=0|' /etc/lightdm/lightdm.conf
    sed -i 's|#autologin-in-background=.*|autologin-in-background=false|' /etc/lightdm/lightdm.conf
    sed -i 's|#user-session=.*|user-session=default|' /etc/lightdm/lightdm.conf
    sed -i 's|#greeter-session=.*|greeter-session=slick-greeter|' /etc/lightdm/lightdm.conf

}

add_commands() {

    echo ">>> adding bashrc"
    echo "" > /home/$user/.bashrc

    if grep -q workstation /root/list; then
        echo "eval $(starship init bash)" >> /home/$user/.bashrc
    fi

    cat >> /home/$user/.bashrc << EOF
export QT_IM_MODULE=ibus
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus

alias search='sudo apk search'
alias install='sudo apk add'
alias update='sudo apk update && sudo apk upgrade'
alias remove='sudo apk del'
alias c='clear'

alias fwupd='fwupdmgr get-devices && fwupdmgr refresh && fwupdmgr get-updates && fwupdmgr update'
alias youtube='yt-dlp -o \"~/%(title)s.%(ext)s\" -f \"bv[vcodec~=\"^((he|a)vc|h26[45])\"][height<=1080][fps<=60]+ba\" --merge-output-format mp4 --downloader ffmpeg --external-downloader ffmpeg --external-downloader-args ffmpeg:\"-ss 00:00:00 -to 00:00:00\"'
EOF

    if grep -q gnome /root/list; then
        editor=gedit
    elif grep -q kde /root/list; then
        editor=kate
    elif grep -q mate /root/list; then
        editor=pluma
    fi

    echo "alias edit='SUDO_EDITOR=$editor sudoedit'" >> /home/$user/.bashrc

}

install_mkinitfs() {

    echo ">>> installing mkinitfs"

    modules=(base nvme ata ide scsi usb lvm ext4 kms mmc keymap)
    modules+=(i915 intel_agp)
    modules+=(amdgpu)
    modules+=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)

    if grep -q btrfs /root/list; then
        modules+=(btrfs)
    fi

    if grep -q zfs /root/list; then
        modules+=(zfs)
    fi

    if grep -q xfs /root/list; then
        modules+=(xfs)
    fi

    if grep -q ext4 /root/list; then
        modules+=(ext4)
    fi

    list=''
    for i in ${!modules[@]}; do
        list+=${modules[$i]}
        list+=' '
    done

    echo ">>> configuring mkinitfs"
    echo "features=\"$list\"" > /etc/mkinitfs/mkinitfs.conf

    echo ">>> building initial ramdisk"
    mkinitfs -b / -f /etc/fstab -C lz4

}

install_syslinux() {

    echo ">>> installing syslinux"
    apk add syslinux
    dd bs=440 count=1 conv=notrunc if=/usr/share/syslinux/gptmbr.bin of=$drive
    mkdir -p /boot/extlinux/
    extlinux --install /boot/extlinux/

}

install_grub() {

    echo ">>> installing grub bootloader"
    apk fix
    apk add grub grub-efi
    grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id="alpine" --no-floppy

    if [[ ! -d /boot/grub/themes/ ]]; then
        mkdir /boot/grub/themes
    fi

    if [[ ! -d /boot/grub/themes/grub-theme/ ]]; then
        echo ">>> cloning grub-theme"
        git clone https://github.com/0free/grub-theme.git
        mv grub-theme/ /boot/grub/themes/
    fi

    sed -i 's|CLASS=".*"|CLASS="--class $( . /etc/os-release; echo "$ID")"|' /etc/grub.d/10_linux
    sed -i "s|menuentry '\$LABEL'|menuentry '\$LABEL' --class efi|" /etc/grub.d/30_uefi-firmware

    cat > /etc/default/grub << EOF
loglevel=0
GRUB_DEFAULT=0
GRUB_TIMEOUT=1
GRUB_SAVEDEFAULT=TRUE
GRUB_DISABLE_RECOVERY=TRUE
GRUB_THEME="/boot/grub/themes/grub-theme/theme.txt"
GRUB_DISABLE_OS_PROBER=FALSE
GRUB_DISABLE_SUBMENU=TRUE
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash=silent mitigations=off"
GRUB_CMDLINE_LINUX=""
EOF

    list='usb usb_keyboard msdospart part_gpt part_msdos part_apple chain ntfs'

    if grep -q btrfs /root/list; then
        list+=' btrfs'
    fi

    if grep -q xfs /root/list; then
        list+=' xfs'
    fi

    if grep -q zfs /root/list; then
        echo "export ZPOOL_VDEV_NAME_PATH=YES" > /etc/profile.d/zpool_vdev_name_path.sh
        source /etc/profile.d/zpool_vdev_name_path.sh
        echo "Defaults env_keep += \"ZPOOL_VDEV_NAME_PATH\"" >> /etc/sudoer
        list+=' zfs zfscrypt zfsinfo'
    fi

    echo "GRUB_PRELOAD_MODULES=\"$list\"" >> /etc/default/grub

    echo ">>> making grub config"
    grub-mkconfig -o /boot/grub/grub.cfg

    echo ">>> checking grub-probe"
    grub-probe /
    grub-probe -t fs -d $root_drive
    grub-probe -t fs_label -d $root_drive

}

finish() {

    echo ">>> cleaning apks"
    apk del *-doc
    echo ">>> installation is completed"
    rm -r /root/*
    echo '' > /root/reboot
    eval $(exit && chroot / bash /root/install)

}

reboot_system() {

    echo ">>> un-mounting /mnt"
    umount -Rfl /mnt
    if grep -q zfs /root/list; then
        zfs umount -a && zpool export $pool
    fi
    read -p ">>> press enter to reboot"
    reboot

}

set -e

if [[ -f /mnt/root/chroot ]]; then

    cp /root/install /mnt/root/install
    chroot /mnt /bin/bash /root/install

else

    if [[ -f /root/list ]]; then
        drive=$(. /root/list; echo $drive)
        boot_drive=$(. /root/list; echo $boot_drive)
        swap_drive=$(. /root/list; echo $swap_drive)
        root_drive=$(. /root/list; echo $root_drive)
    fi

    if [[ -f /root/chroot ]]; then
        if [ $(find /home -maxdepth 1 -type d | wc -l) -ne 1 ]; then
            USER=$(ls /home)
            setup_desktop
        else
            configure
        fi
    else
        if mountpoint -q /mnt; then
            if [[ -f /mnt/root/reboot ]]; then
                reboot_system
            elif [[ -f /mnt/boot/initramfs-* ]]; then
                install_packages
            elif [[ -d /mnt/root/ ]]; then
                setup_linux
            else
                install_base
            fi
        else
            clear
            setup_drive
        fi
    fi

fi

#end
