#!/bin/bash

bootSize='199MiB'
swapSize='4096MiB'
timezone='Asia/Muscat'
mirror='https://dl-cdn.alpinelinux.org/alpine'
arch='x86_64'
branch='edge'
version='v3.16'
pool='rpool'
hostname='linux'
user='user'
password='0000'

packages_list() {

    packages+=(
        # desktop
        busybox musl musl-locales openrc openrc-bash-completion
        dbus dbus-openrc dbus-x11 iio-sensor-proxy
        ibus ibus-bash-completion
        udev-init-scripts udev-init-scripts-openrc
        eudev eudev-openrc eudev-libs
        xorg-server mesa-dri-gallium xf86-input-libinput
        polkit polkit-openrc polkit-elogind polkit-common polkit-elogind-libs
        elogind elogind-openrc elogind-bash-completion
        # hardware
        hwids hwids-net hwids-pci hwids-usb hwids-udev
        # wayland
        xwayland
        # efi boot
        efibootmgr
        # base
        sudo bash bash-completion build-base fakeroot shadow rsyslog rsyslog-openrc sed attr dialog which grep util-linux util-linux-openrc util-linux-login util-linux-bash-completion pciutils usbutils binutils findutils readline lsof less nano curl wget coreutils gawk diffutils autoconf
        # utilities
        openssl ncurses-dev
        # git
        git git-bash-completion
        # compression
        brotli zstd zlib zip lz4 lzo unzip xz bzip2
        # disks
        e2fsprogs lvm2 os-prober gptfdisk dosfstools mtools ntfs-3g ntfs-3g-progs xfsprogs hfsprogs exfatprogs f2fs-tools udftools sfdisk sgdisk udisks2 mmc-utils jfsutils
        # network
        networkmanager networkmanager-openrc networkmanager-common networkmanager-bash-completion networkmanager-elogind
        # firewall
        gufw ufw ufw-openrc ufw-bash-completion iptables iptables-openrc
        # sound
        alsa-plugins-pulse alsa-lib
        pipewire pipewire-media-session pipewire-alsa pipewire-libs pipewire-pulse pipewire-tools
        # bluetooth
        bluez-alsa bluez-alsa-openrc bluez-alsa-utils
        # trackpad
        xf86-input-synaptics xf86-input-mtrack
        # browser
        chromium chromium-chromedriver chromium-swiftshader
        # fonts
        font-hack font-adobe-source-code-pro
        font-arabic-misc font-noto-arabic
        font-inter font-opensans font-roboto font-xfree86-type1
        ttf-font-awesome ttf-dejavu ttf-freefont ttf-droid
        font-awesome font-awesome-free font-awesome-brands
        # keyboard
        setxkbmap
        # timezone
        tzdata
        # gvfs
        gvfs gvfs-afc gvfs-archive gvfs-dev gvfs-fuse gvfs-mtp gvfs-nfs gvfs-smb
    )

    if grep -q btrfs /root/list; then
        packages+=(
            # btrfs
            btrfs-progs btrfs-progs-extra btrfs-progs-libs btrfs-progs-bash-completion
            snapper snapper-bash-completion
        )
    fi

    if ! grep -q VirtualBox /root/list; then
        packages+=(
            # hardware
            bolt pciutils
            tpm2-tools tpm2-tools-bash-completion
            # firmware
            fwupd fwupd-openrc fwup-bash-completion fwupd-efi fwupd-plugin-bios fwupd-plugin-cpu fwupd-plugin-tpm fwupd-plugin-nvme fwupd-plugin-ata
            # mesa
            mesa mesa-vulkan-layers
            # intel GPU
            mesa-vulkan-intel intel-media-driver
            # vulkan
            vulkan-loader vulkan-tools vulkan-validation-layers
            # nvidia GPU
            nvidia-src
            # wireless
            wireless-regdb wireless-tools iwd iwd-openrc
            # network
            ethtool ethtool-bash-completion rsync rsync-openrc
            networkmanager-wwan networkmanager-wifi networkmanager-bluetooth networkmanager-openvpn networkmanager-initrd-generator
        )
    else
        packages+=(
            virtualbox-guest-additions virtualbox-guest-additions-openrc virtualbox-guest-additions-x11
        )
    fi

    if grep -q gnome /root/list; then
        packages+=(
            # gnome session
            gdm gdm-openrc mutter mutter-schemas gnome-desktop gnome-desktop-lang gnome-session gnome-shell gnome-shell-schemas gnome-shell-extensions gnome-menus gnome-initial-setup gnome-control-center gnome-control-center-bash-completion gnome-tweaks gnome-colors-common gsettings-desktop-schemas udisks2-bash-completion tracker-bash-completion pinentry-gnome gst-plugin-pipewire
            # connector
            chrome-gnome-shell gnome-browser-connector
            # theme
            adwaita-icon-theme hicolor-icon-theme
            # gnome tools
            gnome-keyring gnome-terminal gnome-disk-utility gnome-system-monitor file-roller
            # nautilus
            nautilus
            # text
            gedit gedit-plugins py3-cairo
            # firmware
            gnome-firmware-updater
            # gnome theme
            arc-theme arc-dark arc-dark-gnome
            # gedit spell check
            aspell hunspell hunspell-en nuspell
            # network
            network-manager-applet
        )
    fi

    if grep -q kde /root/list; then
        packages+=(
            # sddm
            sddm sddm-openrc sddm-kcm sddm-breeze
            # plasma
            plasma-desktop plasma-workspace plasma-workspace-lang plasma-integration plasma-systemmonitor plasma-firewall plasma-settings plasma-browser-integration plasma-thunderbolt plasma-disks
            # required
            polkit-kde-agent-1 xdg-user-dirs pinentry-qt kde-cli-tools kio-fuse kconfig
            # system
            systemsettings ksysguard
            # kwallet
            kwallet kwallet-pam kwalletmanager kio-kwallet
            # theme
            kiconthemes breeze breeze-gtk breeze-icons
            # bluetooth
            bluedevil
            # power
            powerdevil
            # wayland
            plasma-wayland-protocols kwayland kwayland-integration
            # network
            plasma-nm
            # firewall
            iproute2 net-tools
            # audio
            plasma-pa kmix
            # kde
            ki18n kwin kinit kcron kdecoration krecorder kscreen kscreenlocker kactivities kmenuedit konsole kde-gtk-config
            # file manager
            dolphin dolphin-plugins kfind
            # text
            kate
            # archive
            ark
            # software
            discover discover-backend-apk discover-backend-flatpak discover-backend-fwupd
        )
    fi

    if grep -q workstation /root/list; then

        if grep -q gnome /root/list; then
            packages+=(
                # gnome apps
                gnome-software gnome-software-plugin-apk gnome-software-plugin-flatpak gnome-photos gnome-music gnome-clocks gnome-contacts gnome-calculator gnome-maps gnome-logs gnome-remote-desktop gnome-screenshot gnome-boxes gnome-calendar gnome-sound-recorder gnome-font-viewer gnome-colors gnome-bluetooth gnome-podcasts gnome-characters gnome-builder gnome-shortwave getting-things-gnome sushi simple-scan
                # config
                dconf dconf-bash-completion dconf-editor dconf-editor-bash-completion
                # web
                epiphany
                # documents
                evince evince-nautilus
                # photos
                gthumb eog shotwell
                # mail
                geary
                # sound
                gnome-metronome lollypop blanket
                # other
                glade ghex baobab confy
                # bluetooth
                blueman
                # flatpak
                xdg-desktop-portal xdg-desktop-portal-gnome xdg-desktop-portal-gtk xdg-user-dirs
            )
        fi

        if grep -q kde /root/list; then
            packages+=(
                # plasma
                plasma-camera plasma-videoplayer plasma-phonebook
                # kde
                shelf knetattach kmail ktorrent kdeconnect akregator kphotoalbum kmymoney kdeedu-data kalk rocs calligra marble clip buho vvave communicator qrca step kmousetool kclock krename kcolorchooser kunitconversion
                # widgets
                kconfigwidgets
                # print
                print-manager
                # screen
                spectacle kscreenlocker kruler
                # image
                gwenview
                # audio
                juk kwave elisa
                # video
                kmediaplayer kdenlive dragon haruna
                # YouTube
                plasmatube audiotube
                # camera
                kamera kamoso
                # spelling
                sonnet
                # office
                kcalc okular skanlite
                # input
                plasma-remotecontrollers
                # draw
                kolourpaint
                # math
                cantor kalgebra kig kmplot
                # music
                minuet
                # flatpak
                xdg-desktop-portal xdg-desktop-portal-kde xdg-user-dirs
                # hex
                okteta
            )
        fi

        packages+=(
            # shell
            starship
            # wine
            wine vkd3d
            # thumbnail
            ffmpegthumbnailer
            # mkimage
            abuild alpine-sdk apk-tools alpine-conf mkinitfs xorriso squashfs-tools
            # fonts tools
            font-manager font-viewer
            # office
            libreoffice-base libreoffice-common libreoffice-writer libreoffice-math libreoffice-calc libreoffice-draw libreoffice-lang-en_us libreoffice-lang-ar
            # google
            google-authenticator
            # mail
            thunderbird
            # music
            amberol musescore
            # audio
            ardour tenacity calf calf-jack calf-lv2
            # video edit
            shotcut pitivi x265
            # video subtitle
            gaupol
            # book
            foliate
            # openvc
            opencv py3-opencv
            # python
            black
            # JavaScript
            npm npm-bash-completion nodejs esbuild reason
            # code
            code-oss code-oss-bash-completion lapce codeblocks
            # code format
            prettier tidyhtml
            # html/css to pdf
            weasyprint
            # screenshot
            flameshot
            # electronic
            kicad
            # screen
            obs-studio kooha peek
            # video
            mplayer totem celluloid
            # photos
            krita gimp inkscape gmic curtail
            # printer
            cups cups-openrc cups-pdf bluez-cups
            # driver
            xinput ccid solaar piper
            # math
            mathjax2
            # finance
            homebank
            # 2d
            tiled
            # 3d
            blender freecad godot leocad solvespace goxel
            # 3d printer
            cura
            # text editor
            kakoune
            # mauikit
            mauikit mauikit-accounts mauikit-filebrowsing mauikit-imagetools mauikit-texteditor
            # bitcoin
            bitcoin bitcoin-openrc
            # game emu
            pcsx2 dolphin-emu xwiimote pcsxr
            # rust
            rust rustfmt rust-analysis cargo
            # go
            go
            # php
            composer php82 php82-bcmath php82-bz2 php82-cgi php82-curl php82-common php82-phpdbg php82-dom php82-exif php82-fileinfo php82-fpm php82-gd php82-gettext php82-iconv php82-intl php82-litespeed php82-mbstring php82-mysqli php82-mysqlnd php82-opcache php82-openssl php82-phar php82-pear php82-session php82-snmp php82-soap php82-xml php82-zip
            # android
            gradle android-tools android-tools-bash-completion go-mtpfs scrcpy scrcpy-bash-completion
            # iPhone/iPod/mac
            ifuse ideviceinstaller idevicerestore libirecovery libirecovery-progs libideviceactivation libimobiledevice libimobiledevice-progs
            # pdf
            corepdf pdfarranger poppler
            # drives
            onedrive onedrive-openrc
            # twitter
            cawbird
            # Corsair
            ckb-next
            # RGB
            openrgb
            # plan
            planner
            # music player
            amberol sublime-music
            # music server
            navidrome navidrome-openrc
            # youtube
            ffmpeg yt-dlp yt-dlp-bash-completion pipe-viewer-gtk audiotube tartube youtube-viewer-gtk
            # javascript/css
            minify minify-bash-completion
            # photos
            darktable
            # drawing
            drawing
            # remote
            remmina
            # touch
            touchegg touchegg-openrc
            # CPU
            corectrl
            # cctv
            zoneminder zoneminder-openrc
            # iso
            thumbdrives
        )

        if grep -q gnome /root/list; then
            packages+=(
                libreoffice-gnome
            )
        fi

    fi

    if grep -q server /root/list; then
        packages+=(
            # system
            rsyslog rsyslog-openrc rsyslog-mysql rsyslog-tls rsyslog-http
            # SSL/TLS
            certbot
            # php
            php81 php81-bcmath php81-brotli php81-bz2 php81-cgi php81-curl php81-common php81-phpdbg php81-dom php81-exif php81-fileinfo php81-fpm php81-gd php81-gettext php81-iconv php81-intl php81-litespeed php81-mbstring php81-memcache php81-memcached php81-mysqli php81-mysqlnd php81-opcache php81-openssl php81-phar php81-pear php81-redis php81-session php81-snmp php81-soap php81-xml php81-zip php81-pecl-imagick
            # php admin
            phpmyadmin
            # database
            mariadb
            # mail
            postfix postfix-openrc postfix-mysql postfix-pcre postfixadmin
            dovecot dovecot-openrc dovecot-submissiond dovecot-ldap dovecot-lmtpd dovecot-pop3d dovecot-sql dovecot-mysql
            opendkim opendkim-utils
            cyrus-sasl
            # tools
            imagemagick redis redis-openrc memcached memcached-openrc
            # server
            litespeed litespeed-openrc
            # http
            hetty
            # cab
            cabextract
        )
    fi

}

menu() {

    echo -e "\n --> $1:\n"
    output=$2
    shift 2
    options=($@)
    i=0
    while true; do
        for option in ${options[@]}; do
            if [[ $option == ${options[$i]} ]]; then
                echo -e "\t\e[7m$option\e[0m"
            else
                echo -e "\t$option"
            fi
        done
        read -sn3 key
        if [[ $key == $(echo -en "\e[A") ]] && [[ $i -gt 0 ]]; then
            i=$(($i-1))
        elif [[ $key == $(echo -en "\e[B") ]] && [[ $i -lt ${#options[@]} ]]; then
            i=$(($i+1))
        elif [[ -z $key ]]; then
            break
        fi
        echo -en "\e[${#options[@]}A"
    done
    printf -v $output "${options[$i]}"

}

setup_drive() {

    echo '# created by Saif AlSubhi'
    printf -- '-%.0s' {1..100}; echo ''
    lsblk -o name,type,fstype,size,fsused,fsuse%,mountpoint,label,model
    printf -- '-%.0s' {1..100}; echo ''

    drives=($(ls /dev/ | grep '^nvme.\{3\}$\|^sd.\{1\}$'))

    for i in ${!drives[@]}; do
        drives[$i]="/dev/${drives[$i]}"
    done

    menu 'select a drive' drive ${drives[@]}

    if ls $drive* | grep -q "$drive.\{1\}$"; then
        partitions=($(ls $drive*))
        menu 'select a root partition or use the complete drive ' partition ${partitions[@]}
        if [[ $drive != $partition ]] ; then
            root_drive=$partition
            partitions=($(ls $drive* | grep -v $drive | grep -v $partition | grep "$drive.\{1\}$"))
            menu 'select a boot partition to mount ' partition ${partitions[@]}
            boot_drive=$partition
        fi
    fi

    filesystems=(btrfs zfs xfs ext4 exfat ntfs)
    menu 'select a filesystem' filesystem ${filesystems[@]}

    computers=(minimal workstation server VirtualBox)
    menu 'select a computer' computer ${computers[@]}

    desktops=(gnome kde none)
    menu 'select a desktop' desktop ${desktops[@]}

    bootloaders=(grub refind clover syslinux)
    menu 'select a bootloader' bootloader ${bootloaders[@]}

    echo -e "\n"

    echo ">>> adding options"
    echo "drive=$drive" > /root/list
    echo "filesystem=$filesystem" >> /root/list
    echo "computer=$computer" >> /root/list
    echo "desktop=$desktop" >> /root/list
    echo "bootloader=$bootloader" >> /root/list

    if ! test sgdisk; then
        echo ">>> installing sgdisk"
        apk add sgdisk
    fi

    if [[ ! $root_drive ]]; then

        echo ">>> wiping filesystm"
        wipefs -a -f $drive
        echo ">>> deleting partitions"
        sgdisk -Z $drive
        echo ">>> creating GPT"
        sgdisk -U $drive

        echo ">>> creating boot partition"
        sgdisk -n 0:0:+$bootSize -c 0:efi -t 0:ef00 $drive
        if ls $drive | grep nvme; then
            boot_drive=$drive"p1"
        else
            boot_drive=$drive"1"
        fi
        echo "boot_drive=$boot_drive" >> /root/list

        if [[ $swapSize != '0' ]]; then
            echo ">>> creating swap partition"
            sgdisk -n 0:0:+$swapSize -c 0:swap -t 0:8200 $drive
            if ls $drive | grep nvme; then
                swap_drive=$drive"p2"
            else
                swap_drive=$drive"2"
            fi
            echo "swap_drive=$swap_drive" >> /root/list
        fi

        echo ">>> creating root partition"
        if grep -q zfs /root/list; then
            sgdisk -n 0:0:0 -c 0:$pool -t 0:bf00 $drive
        else
            sgdisk -n 0:0:0 -c 0:linux -t 0:8300 $drive
        fi
        if ls $drive | grep nvme; then
            root_drive=$drive"p3"
        else
            root_drive=$drive"3"
        fi
        echo "root_drive=$root_drive" >> /root/list

        echo ">>> reading partition tables"
        mdev -s

        echo ">>> creating boot filesystem"
        mkfs.vfat -F32 -n BOOT $boot_drive

        if [[ $swap_drive ]]; then
            echo ">>> creating swap filesystem"
            mkswap $swap_drive
        fi

    fi

    echo ">>> creating root filesystem"
    if grep -q zfs /root/list; then
        create_zfs
        set_zfs
    elif grep -q btrfs /root/list; then
        mkfs.btrfs -f -L btrfs $root_drive
        modprobe btrfs
        btrfs subvolume create $boot_drive
    elif grep -q ext4 /root/list; then
        mkfs.ext4 -f -L ext4 $root_drive
    elif grep -q exfat /root/list; then
        mkfs.exfat -f -L exfat $root_drive
    elif grep -q ntfs /root/list; then
        mkfs.ntfs -f -C -L ntfs $root_drive
    elif grep -q xfs /root/list; then
        mkfs.xfs -f -L xfs $root_drive
    fi

    mount_root
    mount_boot
    install_base

}

create_zfs() {

    echo ">>> loading ZFS modules"
    /sbin/modprobe zfs
    echo ">>> checking ZFS modules"
    if ! lsmod | grep -qi zfs; then
       echo 'ERROR: ZFS modules are missing'
       create_rootfs
    fi
    echo ">>> creating ZFS pool"
    zpool create -f -o ashift=12 -o autotrim=on \
    -o cachefile=/etc/zfs/zpool.cache \
    -O recordsize=8192 -O compression=lz4 -O acltype=posixacl \
    -O devices=off -O xattr=sa -O relatime=off -O atime=off \
    -O dnodesize=legacy -O normalization=formD \
    -O canmount=noauto -O mountpoint=legacy -R /mnt $pool $root_drive
    echo ">>> checking ZFS pool"
    zpool status

}

set_zfs() {

    echo ">>> setting ZFS pool as rootfs"
    zpool set bootfs=$pool $pool
    echo ">>> setting ZFS cache"
    mkdir -p /mnt/etc/zfs
    cp /etc/zfs/zpool.cache /mnt/etc/zfs/zpool.cache
    echo ">>> adding ZFS options"
    mkdir -p /mnt/etc/modprobe.d/
    echo "options zfs l2arc_noprefetch=0" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs l2arc_write_max=536870912" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs l2arc_write_boost=1073741824" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs l2arc_headroom=12" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_arc_max=1073741824" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_arc_min=268435456" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_prefetch_disable=0" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_top_maxinflight=320" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_txg_timeout=15" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_scheduler=deadline" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_async_read_min_active=8" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_async_read_max_active=32" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_async_write_min_active=8" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_async_write_max_active=32" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_sync_write_min_active=8" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_sync_write_max_active=32" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_sync_read_min_active=8" >> /mnt/etc/modprobe.d/zfs.conf
    echo "options zfs zfs_vdev_sync_read_max_active=32" >> /mnt/etc/modprobe.d/zfs.conf

}

mount_root() {

    if grep -q zfs /root/list; then
        echo ">>> exporting zpool"
        zpool export $pool
        echo ">>> importing zpool"
        zpool import $pool -d $root_drive -R /mnt
        echo ">>> mounting zfs dataset"
        mount -t zfs $pool /mnt
    else
        echo ">>> mounting root drive"
        mount -o compress=lz4 $root_drive /mnt
    fi

    if ! mountpoint -q /mnt; then
        exit
    fi

    if [[ ! -d /mnt/boot ]]; then
        mkdir -p /mnt/boot
    fi

    if [[ ! -d /mnt/boot/EFI ]]; then
        mkdir -p /mnt/boot/EFI
    fi

}

mount_boot() {

    echo ">>> mounting boot drive"
    mount $boot_drive /mnt/boot

}

install_base() {

    echo ">>> updating packages"
    echo "$mirror/$branch/main" > /etc/apk/repositories
    echo "$mirror/$branch/community" >> /etc/apk/repositories
    echo "$mirror/$branch/testing" >> /etc/apk/repositories
    echo "$mirror/$version/main" >> /etc/apk/repositories
    echo "$mirror/$version/community" >> /etc/apk/repositories

    echo ">>> installing alpine-base"
    apk add --root=/mnt --initdb alpine-base --keys-dir /etc/apk/keys --repositories-file /etc/apk/repositories

    echo ">>> copying repositories"
    cp /etc/apk/repositories /mnt/etc/apk/repositories

    echo ">>> creating /dev/null"
    rm /mnt/dev/null
    cp /dev/null /mnt/dev/null
    chmod 0666 /mnt/dev/null

    echo ">>> loading modules"
    /sbin/modprobe efivars

    set_network
    set_fstab
    setup_linux

}

set_network() {

    echo ">>> adding name resolution"
    echo 'nameserver 10.0.254.3' >> /mnt/etc/resolv.conf
    echo 'nameserver 1.0.0.1' >> /mnt/etc/resolv.conf
    echo 'nameserver 8.8.8.8' >> /mnt/etc/resolv.conf

    echo ">>> adding interfaces"
    cat > /mnt/etc/network/interfaces << EOF
auto lo
iface lo inet loopback
EOF

}

set_fstab() {

    echo ">>> setting fstab"
    echo $filesystem >> /mnt/etc/modules

    if grep -q zfs /root/list; then
        echo "$pool / $filesystem rw,nodev,noauto,xattr,posixacl 0 0" > /mnt/etc/fstab
    elif grep -q btrfs /root/list; then
        echo "$(blkid $root_drive -o export | grep ^UUID=) / $filesystem subvol=@,ssd,nofail,rw,discard,noatime,compress=lz4 0 0" > /mnt/etc/fstab
    else
        echo "$(blkid $root_drive -o export | grep ^UUID=) / $filesystem ssd,nofail,rw,discard,noatime,compress=lz4 0 0" > /mnt/etc/fstab
    fi

    echo "$(blkid $boot_drive -o export | grep ^UUID=) /boot vfat rw,noatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro 0 0" >> /mnt/etc/fstab

    echo "$(blkid $swap_drive -o export | grep ^UUID=) none swap sw 0 0" >> /mnt/etc/fstab

}

setup_linux() {

    install_linux
    install_packages
    set_timezone
    set_host
    change_root

}

install_linux() {

    if [[ -f /mnt/lib/apk/db/lock ]]; then
        rm /mnt/lib/apk/db/lock
        apk fix --root=/mnt
    fi

    list='amd-ucode intel-ucode'
    list+=' linux-pam'

    if grep -q VirtualBox /root/list; then
        if grep -q zfs /root/list; then
            list+=' linux-virt zfs-virt'
        else
            list+=' linux-virt'
        fi
    fi

    if grep -q zfs /root/list; then
        list+=' linux-lts zfs-lts'
        list+=' zfs zfs-openrc zfs-libs'
    else
        list+=' linux-lts linux-edge'
    fi

    if ! grep -q VirtualBox /root/list; then
        list+=' linux-firmware-intel linux-firmware-i915'
        list+=' linux-firmware-amd linux-firmware-amd-ucode'
        list+=' linux-firmware-nvidia'
        list+=' linux-firmware-amdgpu'
        list+=' linux-firmware-other'
        list+=' linux-firmware-brcm linux-firmware-qca'
        list+=' linux-firmware-rtlwifi linux-firmware-rtl_bt linux-firmware-rtl_nic'
    fi

    echo ">>> installing linux"
    apk add --root=/mnt $list

}

install_packages() {

    echo ">>> packages list"
    packages=''
    packages_list

    list=''
    for i in ${!packages[@]}; do
        list+=' '
        list+=${packages[$i]}
    done
    echo ">>> installing packages"
    apk add --root=/mnt $list
    apk fix --root=/mnt

}

set_timezone() {

    echo ">>> setting timezone"
    if [[ -f /mnt/usr/share/zoneinfo/$timezone ]]; then
        install -Dm 0644 /mnt/usr/share/zoneinfo/$timezone /mnt/etc/localtime
        echo $timezone > /mnt/etc/timezone
    else
        read -p " --- timezone Asia/Muscat: " timezone
        set_timezone
    fi

}

set_host() {

    echo ">>> setting hostname"
    echo "$hostname" > /mnt/etc/hostname
    echo "127.0.0.1 localhost $hostname" > /mnt/etc/hosts
    echo "::1       localhost $hostname" >> /mnt/etc/hosts

}

change_root() {

    echo ">>> copying install script"
    cp /root/list /mnt/root/list
    cp /root/install /mnt/root/install
    echo ">>> changing root"
    echo '' > /mnt/root/chroot
    mount --bind /proc /mnt/proc
    mount --bind /dev /mnt/dev
    mount --bind /sys /mnt/sys
    chroot /mnt /bin/bash /root/install

}

configure() {

    disable_root
    create_user
    setup_desktop

}

disable_root() {

    usermod -s /bin/bash root
    echo ">>> changing root password"
    echo -en "$password\n$password" | passwd root
    echo ">>> disabling root login"
    passwd -l root

}

create_user() {

    echo ">>> creating user"
    if id $user &>/dev/null; then
        userdel $user
    fi
    echo '%wheel ALL=(ALL) ALL' > /etc/sudoers.d/wheel
    chmod 0400 /etc/sudoers.d/wheel
    echo -en "$password\n$password" | adduser -h /home/$user -s /bin/bash -G wheel -g $user $user
    adduser $user video
    adduser $user audio
    adduser $user input
    adduser $user netdev

}

setup_desktop() {

    enable_services
    configure_alpine
    add_commands
    make_initramfs
    if grep -q syslinux /root/list; then
        install_syslinux
    fi
    if grep -q refind /root/list; then
        install_refind
    fi
    if grep -q grub /root/list; then
        install_grub
    fi
    finish

}

enable_services() {

    echo ">>> enabling services"

    rc-update add devfs sysinit
    rc-update add dmesg sysinit
    rc-update add mdev sysinit
    rc-update add hwdrivers sysinit

    rc-update add udev sysinit

    rc-update add localmount boot
    rc-update add lvm boot
    rc-update add swap boot

    rc-update add hwclock boot
    rc-update add modules boot
    rc-update add sysctl boot
    rc-update add hostname boot
    rc-update add bootmisc boot
    rc-update add syslog boot
    rc-update add networking boot

    rc-update add mount-ro shutdown
    rc-update add killprocs shutdown
    rc-update add savecache shutdown

    if grep -q zfs /root/list; then
        rc-update add zfs-import boot
        rc-update add zfs-mount boot
        rc-update add zfs-share boot
        rc-update add zfs-zed boot
        rc-update add zfs-load-key boot
    fi

    if grep -q btrfs /root/list; then
        cat > /etc/init.d/btrfs-scan << EOF
#!/sbin/openrc-run
name="btrfs-scan"
depend() {
  before localmount
}
start() {
  /sbin/btrfs device scan
}
EOF
        chmod +x /etc/init.d/btrfs-scan
        rc-update add btrfs-scan boot
    fi

    if grep -q ext4 /root/list; then
        rc-update add ext4 boot
    fi

    rc-update add dbus default
    rc-update add elogind default
    rc-update add polkit default

    rc-update add udev default
    rc-update add udev-settle default
    rc-update add udev-trigger default
    rc-update add udev-postmount default

    rc-update add rsyncd default
    rc-update add networkmanager default
    rc-update add networkmanager-dispatcher default

    rc-update add bluealsa default
    rc-update add bluetooth default
    rc-update add ufw default

    rc-update add iwd default

    if grep -q VirtualBox /root/list; then
        rc-update add virtualbox-guest-additions default
        rc-update add virtualbox-drm-client default
    else
        rc-update add fwupd default
    fi

    if grep -q gnome /root/list; then
        rc-update add gdm default
    fi

    if grep -q kde /root/list; then
        rc-update add sddm default
    fi

    if grep -q workstation /root/list; then
        rc-update add cupsd default
    fi

    if grep -q server /root/list; then
        rc-update add mariadb default
        rc-update add litespeed default
        rc-update add postfix default
        rc-update add dovecot default
        rc-update add opendkim default
        mkdir /var/mysql && chown -R mysql:mysql /var/mysql
        mkdir /var/log/mysql && chown -R mysql:mysql /var/log/mysql
    fi

}

configure_alpine() {

    echo ">>> configuring alpine"

    sed -i 's|#unicode="NO"|unicode="YES"|' /etc/rc.conf
    sed -i 's|#rc_parallel="NO"|rc_parallel="YES"|' /etc/rc.conf
    sed -i 's|#rc_depend_strict="YES"|rc_depend_strict="NO"|' /etc/rc.conf
    sed -i 's|#rc_logger="NO"|rc_logger="YES"|' /etc/rc.conf
    sed -i 's|#rc_hotplug=".*"|rc_hotplug="!net.*"|' /etc/rc.conf
    sed -i 's|#rc_sighup="NO"|rc_sighup="YES"|' /etc/rc.conf
    sed -i 's|#rc_timeout_stopsec="90"|rc_timeout_Stopsec="0"|' /etc/rc.conf
    sed -i 's|#rc_send_sigkill="YES"|rc_send_sigkill="YES"|' /etc/rc.conf
    sed -i 's|#rc_tty_number=.*|rc_tty_number=24|' /etc/rc.conf

    cat >> /etc/default/libc-locales << EOF
en_US.UTF-8 UTF-8
en_US ISO-8859-1
EOF

    if [[ -d /etc/NetworkManager/ ]]; then
        cat > /etc/NetworkManager/NetworkManager.conf << EOF
[main]
dhcp=internal
plugins=ifupdown,keyfile
[ifupdown]
managed=true
[device]
wifi.backend=iwd
EOF
    fi

    if [ ! -d /etc/pipewire ]; then
        mkdir /etc/pipewire
    fi
    cp /usr/share/pipewire/pipewire.conf /etc/pipewire/
    if ! grep -q 'snd_seq' /etc/modules; then
        echo snd_seq >> /etc/modules
    fi

    if [[ ! -d /usr/share/icons/windows-11-icons/ ]]; then
        echo ">>> cloning Windows-11-icons"
        git clone https://github.com/0free/windows-11-icons.git
        rm -r windows-11-icons/.git
        mv windows-11-icons/ /usr/share/icons/
    fi

    echo ">>> configuring firewall"
    sed -i 's|IPV6=yes|IPV6=no|' /etc/default/ufw
    sed -i 's|"DROP"|"REJECT"|g' /etc/default/ufw
    sed -i 's|ENABLED=no|ENABLED=yes|' /etc/ufw/ufw.conf

    if grep -q kde /root/list; then
        if [[ ! -d kde/ ]]; then
            echo ">>> configuring kde"
            git clone https://github.com/0free/kde.git
            mkdir /home/$user/.config/
            mv /kde/config/* /home/$user/.config/
            rm -r kde/
        fi
    fi

    echo ">>> setting ~/"
    chown -R $user:wheel /home/$user/
    chmod -R 770 /home/$user/

}

configure_lightdm() {

    echo ">>> configuring lightdm"
    sed -i 's|#allow-guest=.*|allow-guest=false|' /etc/lightdm/lightdm.conf
    sed -i 's|#autologin-guest=.*|autologin-guest=false|' /etc/lightdm/lightdm.conf
    sed -i "s|#autologin-user=.*|autologin-user=$user|" /etc/lightdm/lightdm.conf
    sed -i 's|#autologin-user-timeout=.*|autologin-user-timeout=0|' /etc/lightdm/lightdm.conf
    sed -i 's|#autologin-in-background=.*|autologin-in-background=false|' /etc/lightdm/lightdm.conf
    sed -i 's|#user-session=.*|user-session=default|' /etc/lightdm/lightdm.conf
    sed -i 's|#greeter-session=.*|greeter-session=slick-greeter|' /etc/lightdm/lightdm.conf

}

add_commands() {

    echo ">>> adding bashrc"
    echo "" > /home/$user/.bashrc

    cat >> /home/$user/.bashrc << EOF

export QT_IM_MODULE=ibus
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus

alias search='sudo apk search'
alias install='sudo apk add'
alias remove='sudo apk del'
alias update='
sudo apk fix
sudo apk update
sudo apk upgrade
'
alias c='clear'

alias fwupd='fwupdmgr get-devices && fwupdmgr refresh && fwupdmgr get-updates && fwupdmgr update'
alias youtube='yt-dlp -o \"~/%(title)s.%(ext)s\" -f \"bv[vcodec~=\"^((he|a)vc|h26[45])\"][height<=1080][fps<=60]+ba\" --merge-output-format mp4 --downloader ffmpeg --external-downloader ffmpeg --external-downloader-args ffmpeg:\"-ss 00:00:00 -to 00:00:00\"'

PS1='\[\033[1;36m\]\u\[\033[1;31m\]@\[\033[1;32m\]\h:\[\033[1;35m\]\w\[\033[1;31m\]\$\[\033[0m\]'

EOF

}

make_initramfs() {

    echo ">>> installing mkinitfs"

    modules=(base nvme ata ide scsi usb lvm keymap virtio kms mmc)

    if ! grep -q VirtualBox /root/list; then
        modules+=(i915 intel_agp)
        modules+=(amdgpu)
        modules+=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)
    fi

    if grep -q btrfs /root/list; then
        modules+=(btrfs)
    fi

    if grep -q zfs /root/list; then
        modules+=(zfs)
    fi

    if grep -q xfs /root/list; then
        modules+=(xfs)
    fi

    if grep -q ext4 /root/list; then
        modules+=(ext4)
    fi

    list=''
    for i in ${!modules[@]}; do
        list+=${modules[$i]}
        list+=' '
    done

    if [[ ! -d /lib/modules/5.15.63-0-lts/ ]]; then
        echo ">>> create /lib/modules/5.15.63-0-lts/"
        mkdir /lib/modules/5.15.63-0-lts/
    fi

    echo ">>> configuring mkinitfs"
    echo "features=\"$list\"" > /etc/mkinitfs/mkinitfs.conf

    echo ">>> building initial ramdisk"
    mkinitfs -b / -f /etc/fstab

}

install_syslinux() {

    echo ">>> installing syslinux bootloader"
    apk add syslinux
    dd bs=440 count=1 conv=notrunc if=/usr/share/syslinux/gptmbr.bin of=$drive
    mkdir -p /boot/extlinux/
    extlinux --install /boot/extlinux/

}

install_refind() {

    echo ">>> installing rEFInd bootloader"
    apk add refind

    pwd=$(pwd)
    cd /boot/refind/drivers_x64
    curl -LO github.com/pbatard/efifs/releases/download/v1.8/xfs_x64.efi
    curl -LO github.com/pbatard/efifs/releases/download/v1.8/zfs_x64.efi
    curl -LO github.com/pbatard/efifs/releases/download/v1.8/ntfs_x64.efi
    cd $pwd

    refind-install --alldrivers $boot_drive
    mkrlconf
    sed -i 's|||' /boot/refind_linux.conf

    if grep -q zfs /root/list; then
        #sed -i "s|root=.*|root=zfs=$pool|" /boot/refind_linux.conf
    fi

}


install_grub() {

    echo ">>> installing grub bootloader"
    apk fix
    apk add grub grub-efi grub-bash-completion
    grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id="alpine" --no-floppy

    if [[ ! -d /boot/grub/themes/ ]]; then
        mkdir /boot/grub/themes
    fi

    if [[ ! -d /boot/grub/themes/grub-theme/ ]]; then
        echo ">>> cloning grub-theme"
        git clone https://github.com/0free/grub-theme.git
        rm -r grub-theme/.git/
        mv grub-theme/ /boot/grub/themes/
    fi

    sed -i 's|CLASS=".*"|CLASS="--class $( . /etc/os-release; echo "$ID")"|' /etc/grub.d/10_linux
    sed -i "s|menuentry '\$LABEL'|menuentry '\$LABEL' --class efi|" /etc/grub.d/30_uefi-firmware

    cat > /etc/default/grub << EOF
loglevel=0
GRUB_DEFAULT=0
GRUB_TIMEOUT=1
GRUB_SAVEDEFAULT=true
GRUB_DISABLE_RECOVERY=true
GRUB_THEME="/boot/grub/themes/grub-theme/theme.txt"
GRUB_DISABLE_OS_PROBER=false
GRUB_DISABLE_SUBMENU=y
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash=silent mitigations=off"
GRUB_CMDLINE_LINUX=""
EOF

    list='msdospart part_msdos part_gpt part_apple'
    list+=' usb usbms usb_keyboard at_keyboard'
    list+=' linux chain btrfs xfs fat exfat ntfs'

    if grep -q zfs /root/list; then
        list+=' zfs zfscrypt zfsinfo'
    fi

    echo "GRUB_PRELOAD_MODULES=\"$list\"" >> /etc/default/grub

    echo ">>> making grub config"
    grub-mkconfig -o /boot/grub/grub.cfg

    echo ">>> checking grub-probe"
    grub-probe /
    grub-probe -t fs -d $root_drive
    grub-probe -t fs_label -d $root_drive

}

finish() {

    echo ">>> cleaning apks"
    apk del *-doc
    echo ">>> installation is completed"
    echo '' > /root/reboot
    exec $(exit && bash install)

}

reboot_system() {

    echo ">>> un-mounting /mnt"
    umount -Rfl /mnt
    if grep -q zfs /root/list; then
        zfs umount -a
        zpool export $pool
    fi
    reboot

}

set -e

if [[ -f /mnt/root/reboot ]]; then
    reboot_system
else
    if [[ -f /mnt/root/chroot ]]; then
        change_root
    else
        if [[ -f /root/list ]]; then
            drive=$(. /root/list; echo $drive)
            boot_drive=$(. /root/list; echo $boot_drive)
            swap_drive=$(. /root/list; echo $swap_drive)
            root_drive=$(. /root/list; echo $root_drive)
        fi
        if [[ -f /root/chroot ]]; then
            if [ $(find /home -maxdepth 1 -type d | wc -l) -ne 1 ]; then
                USER=$(ls /home)
                setup_desktop
            else
                configure
            fi
        else
            if mountpoint -q /mnt; then
                if [[ -f /mnt/boot/initramfs-* ]]; then
                    install_packages
                elif [[ -d /mnt/root/ ]]; then
                    setup_linux
                else
                    install_base
                fi
            else
                clear
                setup_drive
            fi
        fi
    fi
fi

#end
