#!/bin/bash -e

clear && cd ~

sudo apk update
sudo apk upgrade
sudo apk add build-base busybox fakeroot
sudo apk add syslinux xorriso squashfs-tools git
sudo apk add alpine-sdk apk-tools alpine-conf
sudo apk add mtools dosfstools grub grub-efi

USER=$(whoami)

if ! groups | grep -q abuild; then
 sudo addgroup abuild
fi

if ! groups $USER | grep -q abuild; then
 sudo usermod -a -G abuild $USER
fi

if [[ ! -d ~/.abuild ]]; then
 echo -en '\n' | abuild-keygen -i -a
fi

if [[ ! -d ~/aports ]]; then
 git clone --single-branch -b master https://gitlab.alpinelinux.org/alpine/aports.git
else
 cd ~/aports
 git pull
 cd ..
fi

cd ~/aports/scripts/
curl -LO raw.githubusercontent.com/0free/alpine/1/apkovl.sh
cd ~

chmod +x ~/aports/scripts/apkovl.sh

cat << EOF > ~/aports/scripts/mkimg.linux.sh
profile_linux() {
    output_format='iso'
    image_ext='iso'
    arch='x86_64'
	hostname='alpine'
	initfs_cmdline='modules=loop,squashfs,sd-mod,usb-storage quiet mitigations=off'
	initfs_features='base nvme ata usb bootchart btrfs zfs xfs ext4 f2fs lvm mmc raid scsi squashfs'
	modloop_sign=yes
	grub_mod='disk part_gpt part_msdos linux normal configfile fat'
    boot_addons='amd-ucode intel-ucode'
    initrd_ucode='/boot/amd-ucode.img /boot/intel-ucode.img'
    apkovl='./aports/scripts/apkovl.sh'
    kernel_flavors='lts'
    kernel_addons='xtables-addons zfs'
    apks="\$apks
                alpine-base zfs
                dhcpcd ethtool kbd-bkeymaps
                linux-firmware-other
                linux-firmware-amd linux-firmware-amd-ucode
                linux-firmware-amdgpu linux-firmware-radeon
                linux-firmware-nvidia
                linux-firmware-intel linux-firmware-i915
                linux-firmware-rtl_bt linux-firmware-rtl_nic
                linux-firmware-rtlwifi
                linux-firmware-brcm
                linux-firmware-qca
                util-linux coreutils usbutils
                bash bash-completion sudo nano openssl curl
                network-extras iwd dbus wireless-regdb
                e2fsprogs e2fsprogs-extra
                dosfstools mtools lvm2
                btrfs-progs btrfs-progs-extra
                xfsprogs xfsprogs-extra
                exfatprogs
                nfs-utils ntfs-3g ntfs-3g-progs
                f2fs-tools
                sfdisk sgdisk
                openrc openrc-bash-completion openrc-settingsd openrc-settingsd-openrc
                busybox
                busybox-openrc busybox-mdev-openrc busybox-binsh busybox-suid
                musl musl-utils musl-locales
                dbus dbus-openrc dbus-libs dbus-x11
                ibus ibus-bash-completion
                udev-init-scripts udev-init-scripts-openrc
                eudev eudev-openrc eudev-libs
                hwids-net hwids-pci hwids-udev hwids-usb
                xauth xinit xorg-server xorg-server-common
                xwayland
                mesa mesa-dri-gallium
                vulkan-loader vulkan-tools
                polkit-openrc polkit-common polkit-elogind polkit-elogind-libs
                elogind elogind-openrc elogind-bash-completion
                xf86-input-evdev xf86-input-mtrack xf86-input-synaptics
                plasma-desktop plasma-workspace
                breeze-icons
                sddm sddm-openrc sddm-kcm sddm-breeze
 "
}
EOF

chmod +x ~/aports/scripts/mkimg.linux.sh

sed -i 's|linux-firmware||' ~/aports/scripts/mkimg.base.sh
sed -i 's|wireless-regdb||' ~/aports/scripts/mkimg.base.sh

sh ~/aports/scripts/mkimage.sh \
--profile linux \
--arch x86_64 \
--outdir ~/ \
--workdir ~/alpine \
--repository https://dl-cdn.alpinelinux.org/alpine/edge/main \
--repository https://dl-cdn.alpinelinux.org/alpine/edge/community \
--repository https://dl-cdn.alpinelinux.org/alpine/edge/testing

#end
